"""Remade price field

Revision ID: f04d7b24b3f9
Revises: d62c991c0f27
Create Date: 2024-12-10 16:40:15.911041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04d7b24b3f9'
down_revision = 'd62c991c0f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
